### PR TITLE
Add 2 past holiday themes

### LINKED ISSUE #794: Add Lunar Sale 2020 theme
As requested by The Bay Harbor Butcher#7083
https://discordapp.com/channels/301903094080339968/532283733076869143/682519722796777472

### PR DESCRIPTION
**Pull request by candela97**
Closes #794.

Tested manually and seems to work fine.

### CODE REVIEW

**Comment by MxtOUT** [comment]
Works for me now, I guess you concluded this because there was a character limit of 13 for profile styles.
This has been bumped up since.
Ready to merge when you can confirm that this was the case

**Comment by candela97** [comment]
> Works for me now, I guess you concluded this because there was a character limit of 13 for profile styles.
> This has been bumped up since.
> Ready to merge when you can confirm that this was the case

OK, tested and both options work, but they're still missing preview images!

**Comment by MxtOUT** [comment]
image
Hm, this was tested using the default background, which I don't seem to see when using the lunar theme.

**Comment by candela97** [comment]
Steam forced this animated BG `https://steamcdn-a.akamaihd.net/steamcommunity/public/images/items/1223590/daa4b34582ed6cab1327f247be8d03d92ae8aaaa.jpg`

Since we can choose our own combination of themes and backgrounds now, I didn't bother changing it. I suppose it can be included if the profile has no background.

**Pull request merged**
