### PR TITLE
Add remove from wishlist button to community hub

### LINKED ISSUE #670: Option not working - Show "Add to Wishlist" button on community app hubs
Using extension version 1.3.1
Already check this option, but seems no link node has been added to html

image

image

### PR DESCRIPTION
**Pull request by candela97**
Closes #670 
Some problems:
1. `getAppStatus()` takes a while to get updated app status, so the wrong button may be shown

2. `User.isSignedIn` only checks if the user is logged in based on the current page (in this case steamcommunity), but the user needs to be logged in to steamstore for this feature to work

Also need some ideas on how to style the text that shows in case of failure.

### CODE REVIEW

**Comment by MxtOUT** [comment]
> User.isSignedIn only checks if the user is logged in based on the current page (in this case steamcommunity), but the user needs to be logged in to steamstore for this feature to work

Hm, we can't detect it based on the response, since `success: false` could mean anything.
But fetching another site just to detect that is too much, so I'd just leave it as is

**Comment by Revadike** [comment]
Maybe you can detect user signin status from dynamic store userdata. If all data is empty arrays, I think it's safe to assume the user is logged out from steam store.

**Comment by MxtOUT** [comment]
We'd have to refresh it too, which is also another request

**Comment by Revadike** [comment]
> We'd have to refresh it too, which is also another request

It's not done already? I guess it depends on the cache lifetime.

**Comment by MxtOUT** [comment]
Exactly, so there *may* be a new request.
And even if the cache has just been updated a minute ago, the user could've signed out in this time.
We could detect this probably but the first problem still persists

**Pull request merged**
