### PR TITLE
Add sysreq check

### PR DESCRIPTION
**Pull request by candela97**
It doesn't seem to work, but according to the internet, it did some time ago. Might as well implement it anyway, otherwise the option is just sitting there doing nothing. Perhaps Valve will make it work again?

### CODE REVIEW

**Comment by MxtOUT** [comment]
I'm not sure whether that's the way to handle this.
Users will see the button and wonder why it isn't working

**Comment by Revadike** [comment]
> I'm not sure whether that's the way to handle this.
> Users will see the button and wonder why it isn't working

Perhaps it will motivate @tfedor more to work on it 😄

**Comment by MxtOUT** [comment]
That is actualy part of the [Steam browser protocol](https://developer.valvesoftware.com/wiki/Steam_browser_protocol)

**Comment by candela97** [comment]
> That is actualy part of the [Steam browser protocol](https://developer.valvesoftware.com/wiki/Steam_browser_protocol)

Yeah, it's the same function used in ES.

> I'm not sure whether that's the way to handle this.
> Users will see the button and wonder why it isn't working

Remove/hide the option then? An option that does nothing is equally confusing.

**Comment by MxtOUT** [comment]
I will remove the option then because I don't think that Valve will fix this in any near time.
Thanks for bringing this to attention!

**Pull request closed without merging**
