### PR TITLE
Added back friends commenter

### PR DESCRIPTION
**Pull request by Revadike**
image

Original: https://github.com/tfedor/AugmentedSteam/pull/373 & https://github.com/tfedor/AugmentedSteam/pull/709

Both of these were merged, but never given a chance, as they were removed before the next public version.
I had several strangers asking me for this feature and I'd say it was coming to Augmented Steam, but this is no longer a certainty unfortunately.
Not only that, but my (outdated) userscript version of this feature is one of, if not the, most popular userscript I created.
So, it's safe to assume that this feature is highly desired.

The critique it got was it makes it easy for people to spam comments on profiles. However, I have some counter arguments:
 * these profiles are your steam friends and there should be some trust
 * if you receive a comment that you consider spam, it is a minor inconvenience to delete it (in the future we could even add a spam filter for profile comments)
 * I've added several (new) measures to prevent any malicious use, like limiting the maximum amount of friends at a time and disallowing any links (which was [previously even deemed not neccesary](https://github.com/tfedor/AugmentedSteam/commit/cd093e0600eb21f23576ea6fabb3e3d99cbd78de))
 * all the script's actions are reversible
 * this feature does not increase any dangers, since you can already do this by hand, or grab my create or use existing scripts

All I ask is to give this a chance. If it really causes issues, which I believe it will not (my userscript has been an experiment for this), it can always be removed again.

### CODE REVIEW

**Comment by tfedor** [comment]
Our position on friends commenter has not changed.

**Comment by cfles6415** [comment]
thanks  printf("thx, prgrammer"));

**Comment by Revadike** [comment]
> thanks printf("thx, prgrammer"));

@cfles6415 what do you mean?

**Comment by Revadike** [comment]
Oh boy, how lovely would it have been to have had this feature during the holidays <3

**Comment by B3cold** [comment]
I wish to have this feature. Would make it so great with a feature were you can save list/groups of profiles. I agree with Revadike, would be great during the holidays! Please make it happen <3

**Pull request closed without merging**
