### PR TITLE
Added default community tab

### PR DESCRIPTION
**Pull request by Revadike**
Resolves https://github.com/tfedor/AugmentedSteam/issues/507

### CODE REVIEW

**Comment by Revadike** [comment]
> are not able to get on the right page for these icons anym

Where can I find this?

> Why make this global?

Seems to me, this would be ideal. Every time you visit the community, you should be on your favorite tab.

**Comment by Revadike** [comment]
> For example you are not able to get on the right page for these icons anymore

Works fine here. Can you elaborate more specifically? 
Checkout the regex I am using. I will only replace `https://steamcommunity.com/app/<APPID>/` links specifically.

**Comment by MxtOUT** [comment]
The example was bad, sorry, these links are working as intended.

But imagine someone linking directly to the guides page of a game.

**Comment by Revadike** [comment]
> The example was bad, sorry, these links are working as intended.
> 
> But imagine someone linking directly to the guides page of a game.

Yes? That shouldn't give a problem.

Alternatively, I could also redirect `^https://steamcommunity.com/app/<APPID>/$` to the tab of choice.

**Comment by MxtOUT** [comment]
That's a good idea, yeah

**Comment by Revadike** [comment]
> That's a good idea, yeah

You sure? Because AS doesn't load fast, the redirect won't happen instantly, which looks not elegant nor is resource efficient.

**Comment by MxtOUT** [comment]
I thought you meant only changing links that are directed to the homepage of community, so your css selector would be `=` instead of `^=`

**Pull request merged**
