### PR TITLE
Added steam client links to notification menu

### PR DESCRIPTION
**Pull request by Revadike**
image

Resolves https://github.com/tfedor/AugmentedSteam/issues/466

### CODE REVIEW

**Comment by MxtOUT** [comment]
That looks a bit too full imo

**Comment by Revadike** [comment]
> That looks a bit too full imo

What would you change?

**Comment by tfedor** [comment]
This seems like a duplicate of #489, just doing it a bit differently. Again, seems like only potentially useful feature would be to open Steam chat in client. In that case I'd probably just added another "unread chat messages" option and make that one open in Steam

**Comment by Revadike** [comment]
> This seems like a duplicate of #489, just doing it a bit differently. Again, seems like only potentially useful feature would be to open Steam chat in client. In that case I'd probably just added another "unread chat messages" option and make that one open in Steam

Not duplicate, but very much related. I'd like to easily open anything in steam client. Also see #489.

**Comment by tfedor** [comment]
This is too much. Opening Steam client chat is good option though, so I would add that one as a new link, with Steam icon you used. Combined with 489 we don't need these other options, as there will already be a button to open Steam client.

**Comment by Revadike** [comment]
> This is too much. Opening Steam client chat is good option though, so I would add that one as a new link, with Steam icon you used. Combined with 489 we don't need these other options, as there will already be a button to open Steam client.

Same text, just with steam icon?
I'd prefer how it is now.

**Comment by MxtOUT** [comment]
I will close this now, since this is going into a different direction than the PR intended to go.
Discussion can go into #466

**Pull request closed without merging**
