### PR TITLE
Fixed disabled gift recipients

### PR DESCRIPTION
**Pull request by Revadike**
Resolves https://github.com/tfedor/AugmentedSteam/issues/406

### CODE REVIEW

**Comment by tfedor** [comment]
We're not gonna run extension on /checkout/

**Comment by Revadike** [comment]
Why not?

**Comment by MxtOUT** [comment]
Probably security related due to payment information

**Comment by Revadike** [comment]
> Probably security related due to payment information

There is no personal information on the particular page I am running it. Just a list of friends.

**Comment by Revadike** [comment]
Maybe only allow `https://store.steampowered.com/checkout/?purchasetype=gift`?
It has no private information whatsoever:
image

**Comment by Revadike** [comment]
I made another commit. Please check it out. I think this is a good feature to add.

**Comment by phrostb** [comment]
this is a great idea. i've been using a manual script to do it that someone sent me, if it was an included (optional) feature i would totally use it

**Comment by Revadike** [comment]
@tfedor please give it another chance. Any way we can make this work?

**Pull request closed without merging**
