### PR TITLE
Fix quick and instant sell buttons

### PR DESCRIPTION
**Pull request by MxtOUT**

### CODE REVIEW

**Comment by kriki200** [comment]
Quick sell worked...

**Comment by MxtOUT** [comment]
What do you mean it worked?

**Comment by kriki200** [comment]
image
Used it 4 this one...

**Comment by MxtOUT** [comment]
That transaction was done yesterday, but this PR has already been merged for some time, so the fix is already applied to your installation

**Comment by kriki200** [comment]
Oh ql :D .

**Pull request merged**
