### PR TITLE
Added comment editor

### LINKED ISSUE #382: Steam BBCode Editor
Implement the features from:
 * https://github.com/HHHApps/SteamDiscussionHelper by @HHHApps
 * https://github.com/ZeroUnderscoreOu/SteamBBCodes by @ZeroUnderscoreOu

### PR DESCRIPTION
**Pull request by Revadike**
Original #500
Resolves #382

### CODE REVIEW

**Comment by Revadike** [comment]
> The dynamic insertion of the scripts seems dangerous, do you think that you can find another solution?

Like what? It already has a whitelist. You prefer to have a local copy of the script added to dependencies instead (if that even works)?

**Comment by MxtOUT** [comment]
I'm not sure whether you need that much external scripts tbh.
I think most of it can be done relatively easy without them

**Comment by Revadike** [comment]
I've looked into it. I'm afraid they're required for all of the functionality. These are not external scripts either, but native to steam. I don't think you can do it easily without them.
Luckily no conflicts so far even though it's already half a year old.

**Comment by MxtOUT** [comment]
I'm sorry but you either need to find another solution or let it be.
This remote script insertion won't get through

**Comment by Revadike** [comment]
Then how is this OK?
image

Besides, for security we have the domain whitelist

**Comment by MxtOUT** [comment]
This is a local script

**Comment by Revadike** [comment]
> This is a local script

Would this be a solution? And then strip the unneeded code?

**Comment by Revadike** [comment]
> > This is a local script
> 
> Would this be a solution? And then strip the unneeded code?

@MxtOUT

**Comment by MxtOUT** [comment]
Yeah, you can try that

**Comment by Revadike** [comment]
@MxtOUT implemented your request. Awaiting your review ;)

**Comment by MxtOUT** [comment]
This is too much external code for such a feature

**Comment by MxtOUT** [comment]
I'm afraid I have to close this, since the costs involved with the changes are too high to be useful for AS

**Comment by Revadike** [comment]
Outragous! Too much code is a really weird rejection reason. If you're worried about maintaining it, I'm happy to do that for you.

**Pull request closed without merging**
