### PR TITLE
Added support info

### PR DESCRIPTION
**Pull request by Revadike**
Resolves https://github.com/tfedor/AugmentedSteam/issues/425

image

### CODE REVIEW

**Comment by Revadike** [comment]
> That's cool, since when do you get support info from the app details?

Yeah, I didn't realize this either. At first, I though you only got this from the technical help pages.

**Comment by gekkedev** [comment]
@Revadike would be cool if you'd link [here](https://github.com/tfedor/AugmentedSteam/commit/4d481e402f34f98bcd577b18c82a69752d9bbac8#diff-15ed42559e4714a83925e7b18f2b63ceR1367) where it's from

**Comment by Revadike** [comment]
> @Revadike would be cool if you'd link [here](https://github.com/tfedor/AugmentedSteam/commit/4d481e402f34f98bcd577b18c82a69752d9bbac8#diff-15ed42559e4714a83925e7b18f2b63ceR1367) where it's from

I didn't really use any of your code. Just compare the code, it's all different. I just got the idea from you. Would you like to be credited for that?

**Comment by gekkedev** [comment]
Indeed your code is using different methods to to read the data 😉,
though it uses the same CSS selectors to display the data in a very similar style inside the same HTML tag, causing the same effects when being clicked (except for abbreviating the email prefilling feature).
Crediting is just the legal/ethical side of it; but linking will also help you out later as it is a reference to the original usage example as you and others may want to look it up again for further documentation. Like with anything from Stackoverflow, it's a good practice to add a link as comment.

**Comment by Revadike** [comment]
> though it uses the same CSS selectors to display the data in a very similar style inside the same HTML tag, causing the same effects when being clicked (except for abbreviating the email prefilling feature)

I just copied the same style as the above data (publisher/dev, reviews). I did credit you already for the idea in the original issue. Of course, I mean no disrespect to you or your work. Just pointing out that I actually used nothing from your code. I can add a link to it though. I have no problem with that.

**Comment by gekkedev** [comment]
A link would be fine. 👍

**Comment by Revadike** [comment]
> A link would be fine. 👍

Could you make a pull request for that? This one has already been merged.

**Comment by MxtOUT** [comment]
Let that be my problem

**Comment by tfedor** [comment]
@gekkedev I checked the code and it does not seem to be copied from your user script. While yes, final position might be the same, it's really the natural place for this info.

Since the code is Revadike's own, I don't think it's in order to link to your script. If I missed where the code was copied, please link it to me. We will add you to credits though.

**Pull request merged**
