### PR TITLE
Add load stats button to "All Games" page

### PR DESCRIPTION
**Pull request by candela97**
Also added options for showing stats on wishlist and "All Games" page.

### CODE REVIEW

**Comment by MxtOUT** [comment]
I'm not sure whether that is required, the performance cost is really low even for gigantic libraries

**Comment by candela97** [comment]
I thought it could be useful for people who don't want the text to appear every time. In any case, I'll remove the unneccessary loading text.

**Comment by MxtOUT** [comment]
Well, now there is another text.
Maybe you can turn this into an option

**Comment by candela97** [comment]
But there's no option for wishlist stats, should I add a single option for both or individual options?

**Pull request merged**
