### PR TITLE
Fix some badges page issues

### PR DESCRIPTION
**Pull request by candela97**
The header text alignment issue was reported on AS's chrome store support section.

### CODE REVIEW

**Comment by MxtOUT** [comment]
I'm sorry but I can't even see the problem.
What exact issues are fixed with this PR?

**Comment by candela97** [comment]
Should be reproducible on https://steamcommunity.com/my/badges/
before
註解 2020-01-05 010333

after fix
註解 2020-01-05 010335

es_game_stats still visible after switching back from binder view
註解 2020-01-05 010334

**Comment by MxtOUT** [comment]
image
This is without your fix applied

**Comment by Revadike** [comment]
I have the same issue when using AS:
image

**Comment by candela97** [comment]
Seems like ES worked the same way too, which makes the current code look like a typo
https://github.com/jshackles/Enhanced_Steam/blob/7d4b116941e850a3dafd90eb5372f1921e7a6534/enhancedsteam.js#L8058

**Comment by MxtOUT** [comment]
What looks like a typo?

**Comment by candela97** [comment]
ES used `prepend` which is the same as `HTML.afterBegin` right? So I thought using `HTML.beforeBegin` seems like a typo.

**Comment by MxtOUT** [comment]
I'll trust you both on this one, since it doesn't seem to make a difference on my side

**Pull request merged**
