### PR TITLE
[BG] Updated localization

### PR DESCRIPTION
**Pull request by sappy-steam**
Updated Bulgarian localization according to new content from EN file.

### CODE REVIEW

**Comment by MxtOUT** [comment]
Hey, would you like to become a contributor on POEditor, which immensely simplifies this process?
You can join via this link: https://poeditor.com/join/project/yGk0CFH2Uu

**Comment by sappy-steam** [comment]
What would that mean/change? If you don't mind explaining, please.    On Tuesday, February 25, 2020, 02:20:47 PM GMT+2, MxtOUT <notifications@github.com> wrote:  
 
 
Hey, would you like to become a contributor on POEditor, which immensely simplifies this process?
You can join via this link: https://poeditor.com/join/project/yGk0CFH2Uu

**Comment by MxtOUT** [comment]
POEditor is a translation management platform, making it a lot easier to handle our different translation files.
It's very easy to use and you could be the contributor for Bulgarian there

**Comment by sappy-steam** [comment]
Yeah, OK sound good. Thanks, I'll have a look.
Cheers.
    On Tuesday, February 25, 2020, 02:27:32 PM GMT+2, MxtOUT <notifications@github.com> wrote:  
 
 
POEditor is a translation management platform, making it a lot easier to handle our different translation files.
It's very easy to use and you could be the contributor for Bulgarian there

**Comment by sappy-steam** [comment]
Yeah I joined selected Bulgarian, nothing happened when I was clicking on the link for Bulgarian. I opened the link from this emali again and there is no Bulgarian language anymore. I'd love to use that but I don't seem to understand how it's supposed to work.
I'd appreciate if you help me out a bit. Apologies for bugging you or if I've managed to mess something up.    On Tuesday, February 25, 2020, 02:30:20 PM GMT+2, sad happy <sappy_nirv_bg@yahoo.com> wrote:  
 
  Yeah, OK sound good. Thanks, I'll have a look.
Cheers.
    On Tuesday, February 25, 2020, 02:27:32 PM GMT+2, MxtOUT <notifications@github.com> wrote:  
 
 
POEditor is a translation management platform, making it a lot easier to handle our different translation files.
It's very easy to use and you could be the contributor for Bulgarian there

**Comment by sappy-steam** [comment]
Oh I see it in my dashboard now saying pending I suppose I need to be approved from someone in the project. Though I'd still like it if you could help me out as I've never used that platform.My experience is only with Valve's Steam Translation Server and Crowdin.
Cheers    On Thursday, February 27, 2020, 03:21:35 AM GMT+2, sad happy <sappy_nirv_bg@yahoo.com> wrote:  
 
  
Yeah I joined selected Bulgarian, nothing happened when I was clicking on the link for Bulgarian. I opened the link from this emali again and there is no Bulgarian language anymore. I'd love to use that but I don't seem to understand how it's supposed to work.
I'd appreciate if you help me out a bit. Apologies for bugging you or if I've managed to mess something up.    On Tuesday, February 25, 2020, 02:30:20 PM GMT+2, sad happy <sappy_nirv_bg@yahoo.com> wrote:  
 
  Yeah, OK sound good. Thanks, I'll have a look.
Cheers.
    On Tuesday, February 25, 2020, 02:27:32 PM GMT+2, MxtOUT <notifications@github.com> wrote:  
 
 
POEditor is a translation management platform, making it a lot easier to handle our different translation files.
It's very easy to use and you could be the contributor for Bulgarian there

**Comment by Revadike** [comment]
@sappy-steam once you get accepted it's really straightforward. I don't think you'll need help to understand.

**Comment by MxtOUT** [comment]
@sappy-steam I accepted you, you should be able to make edits now

**Comment by sappy-steam** [comment]
Thank you, not that I'm looking at it I think I've used something similar at some point, can;t recall what or when for but yeah I should be fine as far as getting my head around it.
Now how should I proceed with this in regards to the already submitted pull request https://github.com/tfedor/AugmentedSteam/pull/786 
I suppose it's best I remove it, after I am copying the translations from it or would it be better to let you handle it?    On Friday, February 28, 2020, 07:00:38 PM GMT+2, MxtOUT <notifications@github.com> wrote:  
 
 
@sappy-steam I accepted you, you should be able to make edits now

**Comment by MxtOUT** [comment]
Yeah, you can handle this if you want, thanks

**Comment by sappy-steam** [comment]
Moved translation over to POEditor as per MxtOUT suggestion.

**Pull request closed without merging**
