### PR TITLE
fix some customizer issues

### PR DESCRIPTION
**Pull request by candela97**
1. After unchecking "Recent Updates" from the customizer and reloading the page, the option disappears. Setting a timeout for the customizer seems to fix it.
2. On apps that have the "Reviews" section created by AS, after unchecking the option from the customizer and reloading the page, the option disappears.

### CODE REVIEW

**Comment by Revadike** [comment]
setTimeout seems like a sloppy fix

**Comment by candela97** [comment]
dunno how to deal with it apart from blocking the ajax request :|

**Comment by MxtOUT** [comment]
Why blocking?
You could listen for https://store.steampowered.com/actions/ajaxmarkpartnerevents, which's response will have a `boolean` `success` property

**Comment by candela97** [comment]
I don't know how to work with that :(

I can remove the timeout if it's not ideal, but the fix for the reviews section should be good, since the display style is handled by the customizer.

**Comment by candela97** [comment]
I found an alternative fix: turns out the reason why the recent updates option disappears is because the part that contains the text (section title) loads later, rendering the option invalid, but the node with id `events_root` loads together with the page, so we can just query that and manually insert the required text.

**Pull request closed without merging**
