### PR TITLE
Added SteamDB search button

### LINKED ISSUE #385: Add SteamDB button to specific steam store search queries
Duplicate of issue: https://github.com/SteamDatabase/BrowserExtension/issues/20

Examples:

- https://store.steampowered.com/search/?publisher=ArcaneRaise would link to https://steamdb.info/search/?a=app_keynames&keyname=241&operator=3&keyvalue=ArcaneRaise

- https://store.steampowered.com/search/?term=grand%20theft%20auto would link to https://steamdb.info/search/?a=app&q=grand%2520theft%2520auto&type=-1&category=0

- https://store.steampowered.com/search/?filter=comingsoon would link to https://steamdb.info/upcoming/

Et cetera

### PR DESCRIPTION
**Pull request by Revadike**
Resolves #385

### CODE REVIEW

**Comment by tfedor** [comment]
Why is this feature necessary?
1. if you want to search on SteamDB, you'd go to SteamDB
2. SteamDB already has its own extension for stuff like this

**Comment by Revadike** [comment]
> 1. if you want to search on SteamDB, you'd go to SteamDB

It's a shortcut, just like you have steamdb shortcut buttons for app pages. An example user flow is clicking developer on an app page, which takes you to the steam search, then click the steamdb button to search on steamdb instead. The advantage of steamdb is that it shows you a complete list, even apps that are hidden in the steam store, like games developer's have decommissioned.

> 2. SteamDB already has its own extension for stuff like this

Again, by that logic we shouldn't have a steamdb button for anything. Why care if SteamDB has an extension. I'd like to see this feature here, on Augmented Steam.

**Comment by tfedor** [comment]
Wouldn't that fit better for their extension though? It is in a weird place right now. I would argue having shortcut on app page is more useful then generic search.

**Comment by Revadike** [comment]
> One click less.
Same amount of clicks actually.

> Wouldn't that fit better for their extension though?
Why does it matter that it fits better with their extension. I know it fits well with Augmented Steam and that's all you need to know.

**Comment by tfedor** [comment]
Right now we provide quick way to go to SteamDB app page, from where you can directly search for publisher/developer/other info on SteamDB you need. I am not convinced we need to implement another shortcut at search page.

**Pull request closed without merging**
