### PR TITLE
Add option for moving extra links

### LINKED ISSUE #891: Hide / move the links box
Hi. I really want an option to hide the links box. Or just place it above the Metacritic box (where it's actually at without AugmentedSteam). This is the box I mean: https://imgur.com/xdE0Bfq

Would this be possible to fix?

### PR DESCRIPTION
**Pull request by candela97**
Add a new option to resolve #891.

### CODE REVIEW

**Comment by MxtOUT** [comment]
I feel like we could rather integrate this somehow into the customizer, another option seems overkill

**Comment by candela97** [comment]
Yeah but this is an option that moves stuff around instead of hiding/showing it, dunno if that's suitable for the customizer. How about we decide for the users? Leave Steam's native links at its original place (fix the issue) or leave it as -is (close as wontfix).

**Comment by Revadike** [comment]
How about this idea: When the user clicks the customizer button, each block becomes draggable and a show/hide icon appears inside each block. When a block is hidden and customizer is active, its opacity is 0.5. When the customizer is not active, all these blocks are properly hidden. The tricky part will be the dragging, since you will have to align things neatly.

**Comment by MxtOUT** [comment]
> Yeah but this is an option that moves stuff around instead of hiding/showing it, dunno if that's suitable for the customizer.

True, but I only thought about the 3rd party links as additional options for the customizer, not the location of them.

> How about we decide for the users? Leave Steam's native links at its original place (fix the issue) or leave it as -is (close as wontfix).

Those share / embed buttons are a very niche feature, I don't know why they were moved like this and put together with those 3rd party links.
I'd much rather combine this with @Revadike s idea, but by default leave the share / embed buttons where they originally are and the 3rd party links where they now are (at the top)

**Comment by candela97** [comment]
> by default leave the share / embed buttons where they originally are and the 3rd party links where they now are (at the top)

Should I do this in this PR?

**Comment by MxtOUT** [comment]
I don't think it quite fits the request, since the user wanted to remove it altogether.
But if you remove the "resolve" keyword and treat it as an independent PR we should be fine.

**Comment by MxtOUT** [comment]
I think it'd be better if you open a new PR (provided you still wanna do it)

**Pull request closed without merging**
