### PR TITLE
Simplify parsing prices in addPackBreakdown

### PR DESCRIPTION
**Pull request by candela97**
Related https://github.com/tfedor/AugmentedSteam/pull/802#discussion_r407738491

### CODE REVIEW

**Comment by candela97** [comment]
On a side note, packs are getting fewer and fewer, maybe we should add an option for this, disabled by default...

**Comment by MxtOUT** [comment]
I don't see a reason for that.
What are your concerns? Performance?

**Comment by candela97** [comment]
yeah I was thinking about performance since it seems like a waste to run this on 90% of pages that won't see a difference

**Comment by MxtOUT** [comment]
We're talking about milliseconds here, I don't think it's worth it to create another options for this

**Pull request merged**
