### PR TITLE
Changes to Czech localization file

### PR DESCRIPTION
**Pull request by ondrodrak**

### CODE REVIEW

**Comment by ondrodrak** [comment]
I looked at the localization file for the Czech language and polished it a little

**Comment by candela97** [comment]
Localization is handled on POEditor now, you can find a link to join the group from the About section on the settings page :)

**Comment by ondrodrak** [comment]
thanks, i will look at it

**Comment by MxtOUT** [comment]
If you have requested access, you should be accepted right now

**Pull request closed without merging**
