### PR TITLE
Added Augmented Steam Group

### PR DESCRIPTION
**Pull request by Revadike**
https://steamcommunity.com/groups/augmentedsteam

### CODE REVIEW

**Comment by Revadike** [comment]
I take it you don't want to have a separate steam group for AS? Even with the ITAD steam group flooded with AS issues?

**Comment by MxtOUT** [comment]
The thing is, that you did this without any sorts of previous communication.
And the group should be owned by ITAD

**Comment by Revadike** [comment]
Yeh, I kinda just did this spontaneously in the middle of the night after finding out there exists no ITAD group on steam.
Of course, I can make ITAD owner of the group. Let's make it happen.

**Comment by Revadike** [comment]
I'm proud on how I set up the group, though. I managed to name the group "Augmented Steam" even though Steam claimed it was taken. I was also surprised the url wasn't taken. Also, I wanted the abbreviation to be AS or something like that. Obviously, that was taken too. Luckily, I came up with "By ITAD" and that was perfect. The title now says Augmented Steam By ITAD. A true thing of beaty 😄

**Pull request closed without merging**
