### PR TITLE
Update strings.json

### PR DESCRIPTION
**Pull request by TeknoMobil**
Hi
The profile seems to be corrupt when the translation is long. This way properly

### CODE REVIEW

**Comment by TeknoMobil** [comment]
Sample: 


Correction:

**Comment by Yanuut** [comment]
The translation is done on [POEditor](https://poeditor.com/join/project/yGk0CFH2Uu).

**Comment by TeknoMobil** [comment]
> The translation is done on [POEditor](https://poeditor.com/join/project/yGk0CFH2Uu).

Thank you, I hope the person who approves the translation won't have a problem.

**Comment by TeknoMobil** [comment]
Sorry, I can't join because the complete translation has been done.

**Pull request closed without merging**
