### PR TITLE
Remove broadcasts from store pages

### LINKED ISSUE #508: hide broadcasts from store pages
Example store page currently broadcasting:
https://store.steampowered.com/app/814370/Monster_Sanctuary/

I suggest adding an option to the customize button on store pages to disable the broadcast banner/window, and the mini player that pops up when you scroll down.

There's actually an option in Account Preferences to disable these, but it doesn't seem to work.

### PR DESCRIPTION
**Pull request by Revadike**
Resolves #508

### CODE REVIEW

**Comment by andrewpros** [comment]
So what we only remove application_root now?
I did check it before and it didn't work, oh well maybe i was not fast enough.

Not sure wee need a block for sale pages, they are special ones, so i think there is no issue here.

**Comment by Revadike** [comment]
My tests were positive consistently, but I can see it not being totally reliable. While the stream may not appear visually, if you remove the element too late, it could already have started the process of downloading the stream and it won't stop. A solution is either consistently and reliably removing the element on time (which I hope is currently happening), or while logged in, hide broadcasts via official steam settings, so it won't start autoplaying. Either way, I think the current solution of removing the element is sufficient, but you can also check my alternative solution in this commit: https://github.com/tfedor/AugmentedSteam/pull/663/commits/817fbb72f1163ecc9e27727b92c9da36c33af71c

**Comment by andrewpros** [comment]
Yeah, i was removing it by hand quickly in the inspector after page reload and this is too slow, it already starts downloading stream, but i did a tampermoneky test script and then it always works with removing application_root.

Thing is with the official settings, you need to log in and it wont hide it, it just collapses the bar but u can see it, this is what is irritating for me, so an option like this is better.

**Comment by MxtOUT** [comment]
I prefer the solution of commit 817fbb7, but it still isn't perfect.
Running a code every 100 ms seems hackish, the same thing could probably be achieved with a `MutationObserver` or Ajax Callbacks

**Comment by Revadike** [comment]
> I prefer the solution of commit [817fbb7](https://github.com/tfedor/AugmentedSteam/commit/817fbb72f1163ecc9e27727b92c9da36c33af71c), but it still isn't perfect.
> Running a code every 100 ms seems hackish, the same thing could probably be achieved with a `MutationObserver` or Ajax Callbacks

Not if the goal is to remove it before the video resources are loaded.

**Comment by tfedor** [comment]
> Not if the goal is to remove it before the video resources are loaded.

How is the 100ms interval check faster than mutation observer?

**Comment by Revadike** [comment]
> > Not if the goal is to remove it before the video resources are loaded.
> 
> How is the 100ms interval check faster than mutation observer?

By watching the variables, you can avoid any DOM content from being loaded.

**Comment by andrewpros** [comment]
Oh boy, i got a notification, this isn't still merged, why?

**Comment by MxtOUT** [comment]
Well, it doesn't work for me, the element is removed but the stream is still there

**Comment by Revadike** [comment]
> Well, it doesn't work for me, the element is removed but the stream is still there

Try the solution of the first commit.

**Comment by MxtOUT** [comment]
The problem is that the application_root isn't the element that displays the stream.
I tried for about an hour now to find the initiator of the stream, but minification makes it very, very hard

**Comment by Revadike** [comment]
I think I found it before, but the problem was our code doesn't always execute before the initiator. This issue is a year old, so excuse my memory.

**Comment by Revadike** [comment]
Cool, pleasantly surprised

**Pull request merged**
