### PR TITLE
Add gifting to all friends

### PR DESCRIPTION
**Pull request by Revadike**
Resolves https://github.com/tfedor/AugmentedSteam/issues/406

### CODE REVIEW

**Comment by MxtOUT** [comment]
Why are you calling this a fix, when it's supposed to be an enhancement?

**Comment by MxtOUT** [comment]
What happens if you receive a gift for a game that you already own?

**Comment by Revadike** [comment]
> What happens if you receive a gift for a game that you already own?

You can save it to your inventory and either trade it or gift it to somebody else.

**Comment by MxtOUT** [comment]
I doubt that this will work.
If you have some sort of proof that this indeed works, please reopen this PR

**Comment by Revadike** [comment]
> I doubt that this will work.
> If you have some sort of proof that this indeed works, please reopen this PR

It definitely works. It's being used by gift collectors everywhere... I'll see if I can find a gift for proof, I guess?

**Comment by Revadike** [comment]
I proved it was working

**Comment by MxtOUT** [comment]
I just realized that this runs on the checkout page, which _could_ cause security problems.
Sorry I didn't see that before...

**Comment by Revadike** [comment]
> I just realized that this runs on the checkout page, which _could_ cause security problems.
> Sorry I didn't see that before...

Please give me one example, how in its current form, it can be abused?

**Comment by MxtOUT** [comment]
I don't know, but I'm also not specialized in hacking

**Comment by Revadike** [comment]
I'd also like to point out, it doesn't run at any checkout page, just this one. And this page has no infringing data whatsoever.

**Comment by MxtOUT** [comment]
I know but it's still a part of the checkout process

**Comment by ReptilianWorldOrder** [comment]
I didn't even know this was possible. That's majorly big.

**Comment by Revadike** [comment]
Yeah, I'm sure it will be useful to many!
I added proof here:
https://github.com/tfedor/AugmentedSteam/pull/570#issuecomment-554401388

**Comment by ReptilianWorldOrder** [comment]
> image

I believe it works though I"m looking at something that defies what I thought possible in the years since Valve changed up gifting so much that I'm convinced I'm misunderstanding something.. 

This game is now in their inventory.... and can be sent to other people like any normal steam gift from a few years back... and this process works for like any steam purchase (i mean, sent to an account that already owns the game so it can store as a gift). That's freaking amazing.

**Pull request closed without merging**
